version: '3.8'

services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 5001-5002:5000
